digicatapult/sqnc-identity-service

- .github/release.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- helm/vitalam-identity-service/Chart.yaml
- helm/vitalam-identity-service/values.yaml
- package-lock.json
- package.json
Uses the new [automatic release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) GitHub feature to generate release notes, aka `changelog`, based on PR labels. 
Example auto-generated release notes:
> Automatically generated release notes

- .github/workflows/release.yml
- helm/vitalam-identity-service/Chart.yaml
- helm/vitalam-identity-service/values.yaml
- package-lock.json
- package.json
Uses [github-script](https://github.com/actions/github-script) to delete `tags/latest` so we get a new `latest` release that matches our most recent release.
> Replace rather than update latest release

- .github/workflows/release.yml
- package-lock.json
The release build failed because I missed a secret to add in the `release` workflow
https://github.com/digicatapult/dscp-identity-service/runs/6076978363?check_suite_focus=true
> Add missing secret

- app/util/appUtil.js
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
- test/integration/routes.test.js
Fix the bug where listing a member with an alias fails. This is due to a broken reducer
See https://github.com/digicatapult/dscp-identity-service/runs/6354141761?check_suite_focus=true for failing case
Note this also adds an afterEach to decouple the tests from each other
> IN-249 bug where listing members with aliases fails

- README.md
- app/api-v1/routes/self.js
- app/api-v1/validators/selfResponseValidator.js
- app/env.js
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/templates/configmap.yaml
- helm/dscp-identity-service/templates/deployment.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
- test/helper/routeHelper.js
- test/integration/routes.test.js
Adding a new route `/self` for retrieving `SELF_ADDRESS` env variable or `devDefault`
- api-doc update including route and request validator
- integration test along with other routes
```
routes
authenticated routes
✔ return membership members
✔ return membership members with aliases
✔ update non-existing member alias
✔ update existing member alias
✔ update existing member alias
✔ update alternative non-existing member with duplicate alias
✔ get member by alias
✔ get member by incorrect alias
✔ get member by invalid alias
✔ get member by address
✔ get self address or return default <--- THIS ONE
```
> IN-229: new route /self.

- .github/workflows/release.yml
- .github/workflows/tests.yml
- .gitignore
- README.md
- app/api-v1/routes/members.js
- app/api-v1/routes/members/{address}.js
- app/api-v1/routes/members/{aliasOrAddress}.js
- app/api-v1/routes/self.js
- app/env.js
- app/server.js
- app/util/authUtil.js
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/templates/configmap.yaml
- helm/dscp-identity-service/templates/deployment.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
- test/integration/routes.test.js
Make it so the service can be run with/without authentication based on an env.
Very similar to https://github.com/digicatapult/dscp-api/pull/45 and https://github.com/digicatapult/dscp-api/pull/46
> Add AUTH_TYPE env

- README.md
- app/api-v1/api-doc.js
- app/env.js
- app/server.js
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/templates/configmap.yaml
- helm/dscp-identity-service/templates/deployment.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
Adds the env `EXTERNAL_URL` which if provided will override the url field in the published openapi spec.
> Add configration of EXTERNAL_URL

- app/util/appUtil.js
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
Since `dscp-node` was updated to use a more recent tag of Substrate, we no longer need the `dscp-node` extended types config when connecting to the node via polkadot.js  
This means we can remove usage of `@digicatapult/dscp-node` package and replace with direct use of `@polkadot/api`
> Replace dscp-node package with @polkadot/api

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- helm/dscp-identity-service/Chart.yaml
- helm/dscp-identity-service/values.yaml
- package-lock.json
- package.json
This renames `DSCP` to `Veritable` where appropriate in markdown files.
> Rename DSCP to Veritable

- README.md
- app/env.js
- app/util/authUtil.js
- package-lock.json
- package.json
Add an `AUTH_TYPE: EXTERNAL` that keeps no auth at the service level (default behaviour) but displays swagger authentication options so a `Authorization` header can be added easily. Used when `dscp-identity-service` is deployed to authorise at ingress level rather than service level. 
`AUTH_TYPE=EXTERNAL npm run dev`
> Add external AUTH_TYPE

- app/api-v1/api-doc.js
- app/server.js
- app/util/authUtil.js
- package-lock.json
- package.json
This should fix a bug so we consistently use `BearerAuth` everywhere instead of `bearerAuth`
> Fixing BearerAuth casing everywhere

- app/api-v1/api-doc.js
- app/api-v1/routes/members/{aliasOrAddress}.js
- app/api-v1/routes/self.js
- app/api-v1/services/apiService.js
- app/server.js
- app/util/appUtil.js
- package-lock.json
- package.json
- test/integration/routes.test.js
- For `/self` and `/members` if `alias: null` -> return `alias: {address}` instead
- `GET /members/{address}` still returns a member, even if there's no database alias, as long as the address is a member of the chain
- Return `400` if attempted to set alias of `PUT members/{address}` as an address
> Use address if alias is null

- README.md
---
name: Bug report
about: Create a report to help us improve
---
- Checked the FAQs for common solutions: <https://github.com/digicatapult/dscp-identity-service/blob/main/CONTRIBUTING.md/#FAQs>
- Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Adscp-identity-service>
README.md uses name `veritable` for repositories instead of `dscp`
1. 
2. 
3. 
**Expected behaviour:**
README.md calls repositories `dscp` 
**Actual behaviour:**
README.md calls repositories `veritable`
> Update README.md to use dscp from veritable

- .github/workflows/release.yml
- package-lock.json
- package.json
Fixes the release workflow. Current behaviour: https://github.com/digicatapult/dscp-identity-service/actions/runs/6011088646
> Remove old `check-version` from release workflow

- README.md
- app/api-v1/api-doc.js
- app/env.js
- app/server.js
- package-lock.json
- package.json
Remove `EXTERNAL_ORIGIN` and `EXTERNAL_PATH_PREFIX` as they never worked how we wanted them to serve multiple APIs specs on the same prefix (instead we merge specs with https://github.com/digicatapult/wasp-open-api)
> Remove external origin envs

- Dockerfile
- package-lock.json
- package.json
Ticket: [SQNC-5](https://digicatapult.atlassian.net/browse/SQNC-5)
This is a hangover from #236 where I erroneously removed the migrations from the built docker container. This fixes that. I've validated this against a local build of the container with `sqnc-matchmake-api`
[SQNC-5]: https://digicatapult.atlassian.net/browse/SQNC-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add migrations to docker container

- .depcheckrc
- .gitignore
- .swcrc
- import/hooks.mjs
- import/index.mjs
- package-lock.json
- package.json
- test/mocharc.json
- tsconfig.json
Please delete options that are irrelevant.
https://digicatapult.atlassian.net/browse/SQNC-20
Migrate from using `tsimp` as our typescript runtime compiler to using `swc`
Similar to https://github.com/digicatapult/veritable-ui/pull/172.
Note there's a known bug with `swc-node` where node_modules imports with a package ending in `.js` fails (see https://github.com/swc-project/swc-node/issues/865). We hit this as polkadot.js uses `bn.js` internally. The workaround here involves implementing our own shim that bypasses `swc-node` in this particular case.
Note I've additionally tested brining this up in a built container and it all works
Not upgrading until `swc-node` fixes this. Note though that this bug has been reported for several weeks with no sign of it being fixed. Hence I'm putting this …
> Migrate from tsimp to swc 

- package-lock.json
- package.json
Please delete options that are irrelevant.
https://digicatapult.atlassian.net/browse/SQNC-44
Upgrades supported node version to >=22 and supported npm to >=10
Whilst we were always running on latest lts we previously advertised support for node 20 or higher. We're restricting that now. Technically this is a major version bump as a previously version 20 system would now not be able to run this.
N/A
None
N/A
> Set supported node version to 22

- .swcrc
- Dockerfile
- docker/keycloak/internal.json
- docker/keycloak/sequence.json
- package-lock.json
- package.json
- src/authentication.ts
- src/controllers/v1/members.ts
- src/controllers/v1/self.ts
- src/env.ts
- src/global.d.ts
- src/server.ts
- src/swagger.ts
- test/helper/auth.ts
- test/integration/docs.test.ts
- test/integration/httpServer.test.ts
- test/integration/routes.test.ts
- tsconfig.json
- tsoa.json
Please delete options that are irrelevant.
https://digicatapult.atlassian.net/browse/SQNC-126
Add support for internal authentication
As part of spinning out the attachment API from matchmaker we need services to be able to authenticate internally without having user authentication. This is because the matchmaker indexer needs access to the attachment api which needs access to the identity service.
This change implements a second authentication provider for all routes. Note this is a major version bump because of required environment variables being introduced.
None
This is a major version bump which willl require new environment variables in the helm chart, a new realm in the keycloak instance and new values in the flux repo. These will follow.
None
> Add support for internal authentication

- .depcheckrc
- package-lock.json
- package.json
- src/chainNode.ts
- test/helper/testInstanceChainNode.ts
- test/integration/routes.test.ts
Please delete options that are irrelevant.
SQNC-130
Add support so we can retrieve URLS that were passed in as preimage.
org data values can be set both as a `Literal` (string) and `Preimage` (hash) this PR adds support to an `members/{addr}/org-data` endpoint so that if org data was configured as preimage this will be retrieved. This also allows for a variable length url. 
The current working version returns an empty string if we have used a preimage hash but forgot to change the type from 'Literal' to 'Preimage' when settign the org data.
> retrieving oidcs and attachment if set as preimage
